version: '3.3'

services: 
  php-env:
    build: .
    volumes:
      - ./erp:/var/www/html
    ports:
      - 9000:80
  mysql_db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc@123
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports: 
      - 8000:80
    environment:
     - PMA_ARBITRARY=1 